819 and 820 - one scrollbar to replace right panel and editorLayout
ONSdigital/eq-author-app pull request #1414
Opened 2020-08-21 10:46 UTC by zimboflyman

### What is the context of this PR?

This PR combines EAR 819 and 820
remove individual scrollbars from the right hand panel and editorlayout
create a single scrollbar to contain both

this will work the same for:

- design page
- preview page
- confirmation page
- calcsum page

### How to review 

create a question with enough answers to extend both the editor panel and the right hand panel
This should show a single scrollbar on the far right controlling both
The header will remain sticky
the scroll bar will not affect the nav panel on the left
If you shrink screen height below 680px - a global scroll bar will take over and the entire page including header and left nav will become scrollable
enjoy!

2020-08-24 10:39 UTC, MattElcock requested changes
Scrollbar works perfectly. Nice one! My only reservation is that the properties panel cuts off at the bottom and doesn't span the entire page when you scroll. Can you check this with Joe and see if he wants it fixed as part of this ticket?

![image](https://user-images.githubusercontent.com/15129656/91035892-665c4b80-e5fe-11ea-9de2-5f7b38a19f73.png)

2020-08-25 10:07 UTC, MattElcock approved these changes

2020-08-25 12:23 UTC, jasehumphr approved these changes

2020-08-25 12:39 UTC, jchapman68 commented
Scroll bar only visible in the header when screen height is shrunk so whole page is scrollable.
![20200825_133324](https://user-images.githubusercontent.com/30293265/91175204-5add5300-e6d8-11ea-9c81-45a1f83e90ab.jpg)

2020-08-25 12:51 UTC, merged