Ear 684 disable skip logic on first question
ONSdigital/eq-author-app pull request #1565
Opened 2020-10-29 10:26 UTC by jchapman68

### What is the context of this PR?

> https://collaborate2.ons.gov.uk/jira/browse/EAR-684
> 
> 

### How to review 

> Add to the list below as appropriate, including screenshots when necessary

* Create a questionnaire with a number of questions
* Check the Add skip logic button is disabled only for first question in the questionnaire

### What to do after everything is green

1. * [ ] Bring this branch up-to-date with Origin/Master
2. * [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. * [ ] Click the **Merge** button on this pull request
4. * [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. * [ ] Move the Jira ticket for this task into the next stage of the process

2020-11-03 11:38 UTC, tjamesmac commented on eq-author/src/App/page/Logic/SkipLogic/SkipLogicPage/NoSkipConditions.js
> +        isFirstQuestion={isFirstQuestion}
```suggestion
        isFirstQuestion={isFirstQuestion}
        disabled={isFirstQuestion}
```

2020-11-03 11:43 UTC, tjamesmac approved these changes
Nice one

2020-11-03 11:50 UTC, tbaggaley reviewed
Looks good Josh, just one question. The ticket says that when you remove a question in front and another question with skip logic becomes the first in the questionnaire, "then the skip logic is removed and the button is disabled".

The skip logic isn't being removed when questions become first. But when you remove it the changes work as intended (the new message is displayed etc.)

Just checking if this is needed - should we also remove the skip logic from these questions? Otherwise happy to approve

2020-11-03 11:52 UTC, tjamesmac commented
@tbaggaley yes it is needed good spot!

2020-11-09 07:08 UTC, tbaggaley approved these changes
Looking good; skip conditions are being deleted now on page/section move/delete

2020-11-09 08:39 UTC, tjamesmac submitted a review, later dismissed

2020-11-09 09:21 UTC, MattElcock requested changes
Ignore this. I didn't have the latest changes.

2020-11-09 09:23 UTC, MattElcock submitted a review, later dismissed
Sorry about my earlier review. I didn't have the latest changes. It all looks good. Well done. :)

2020-11-09 15:51 UTC, jasehumphr approved these changes
All good

2020-11-09 16:06 UTC, tbaggaley approved these changes

2020-11-09 16:07 UTC, merged