Ear 1100 move qCode validation client side
ONSdigital/eq-author-app pull request #1772
Opened 2021-02-05 16:21 UTC by zimboflyman

### What is the context of this PR?

Devs agreed that it is better to refactor the QCode validation page due to complexities with the existing implementation. 
Remove all AJV refs to qCodes
Remove qcodeErrorTotals from resolvers
Move all qCode validation to clientside
More answer state (Previously getAllAnswers.graphql) up to QuestionnaireDesignPage
Use React.Context to pass list of answers down to qCode page.
Update Queries in QuestionnaireDesignPage so as update the context when Qcodes are added in qCode page - This will allow us to handle red error dot in mainNav

### How to review
Make a list of all question types
You should see red dot on qCode icon of main menu
Add qCodes to all answers
Red dot should dissappear or reflect missing qcodes

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2021-02-09 10:41 UTC, tbaggaley requested changes
Hey Shane - looking good so far, haven't finished reviewing yet but there's a couple small changes here and one to fix the red dot coming up when parent checkbox answers have empty qCodes (as seen when you import LCS)

2021-02-09 10:41 UTC, tbaggaley commented on eq-author/src/App/QuestionnaireDesignPage/MainNavigation/index.js
> +    find(flattenedAnswers, obj => obj.qCode === "" || obj.qCode === null);
```suggestion
const emptyQCode = flattenedAnswers?.find(({type, qCode}) => type !== "Checkbox" && !qCode);
```

This fixes issue where Checkbox qCodes were coming up as missing (for the parent question) on imported LCS.

2021-02-09 11:10 UTC, zimboflyman commented on eq-author-api/src/validation/index.js
>    let field = "";
haha - makes sense!

2021-02-09 11:15 UTC, tbaggaley requested changes

2021-02-09 11:15 UTC, tbaggaley commented on eq-author/src/App/qcodes/QCodesTable/index.js
> +  }
```suggestion
  if(answers) {
    return answers.map((item, index) =>
      <Row
        key={`${item.id}-${index}`}
        {...item}
        error={duplicates[item.qCode] > 1}
        noValQCodeError={!item.qCode}
      />);
    }
```

2021-02-09 11:56 UTC, tbaggaley requested changes
Could we move `QCodeContext` out into its own file too (like components/QuestionnaireContext)?

It could export a `useQCodeContext()` hook for use in client code elsewhere - like with the questionnaire context one - saves having to directly import the `QCodeContext` / `useContext` on each file

2021-02-09 12:45 UTC, zimboflyman commented on eq-author/src/App/qcodes/QCodesTable/index.js
> +  }
much tidier - ta

2021-02-09 12:47 UTC, zimboflyman commented on eq-author/src/App/qcodes/QCodesTable/index.js
> +  }
much tidier - ta

2021-02-09 13:11 UTC, zimboflyman commented
> components/QuestionnaireContext

Good idea Tom - done

2021-02-09 14:45 UTC, farres1 requested changes

2021-02-09 14:45 UTC, farres1 commented on eq-author/src/App/QuestionnaireDesignPage/MainNavigation/index.test.js
> +import { QCodeContext } from "App/QuestionnaireDesignPage";
```suggestion
import { QCodeContext } from "components/QCodeContext";
```

2021-02-09 14:45 UTC, farres1 commented on eq-author/src/App/qcodes/QCodesTable/index.test.js
> +import { QCodeContext } from "App/QuestionnaireDesignPage";
```suggestion
import { QCodeContext } from "components/QCodeContext";
```

2021-02-09 14:49 UTC, zimboflyman commented on eq-author/src/App/qcodes/QCodesTable/index.test.js
> +import { QCodeContext } from "App/QuestionnaireDesignPage";
Thanks Sam - I just uploaded this - ta!

2021-02-09 14:49 UTC, zimboflyman commented on eq-author/src/App/QuestionnaireDesignPage/MainNavigation/index.test.js
> +import { QCodeContext } from "App/QuestionnaireDesignPage";
thanks Sam - sorted now!

2021-02-10 08:30 UTC, tjamesmac submitted a review, later dismissed
Looks really good Shane, nice one! Just a few formatting issues here and there. Think I highlighted most of them

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/qcodes/QCodesTable/index.js
> +  if(answers) {
```suggestion
  if (answers) {
```

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/qcodes/QCodesTable/index.js
> +  noValQCodeError: PropTypes.bool, // eslint-disable-line
```suggestion
  noValQCodeError: PropTypes.bool,
```

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/qcodes/QCodesTable/index.js
> +  const {flattenedAnswers, duplicates }  = useQCodeContext();
```suggestion
  const { flattenedAnswers, duplicates }  = useQCodeContext();
```

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/utils/getAllAnswersFlatMap.js
> +  } from "constants/answer-types";
```suggestion
import { RADIO } from "constants/answer-types";
```

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/qcodes/QCodesTable/index.test.js
> +  ];
```suggestion
    flattenedAnswers = [
      {
        title: "<p>Questions 1</p>",
        alias: undefined,
        id: "ans-p1-1",
        description: "",
        guidance: "",
        label: "num1",
        qCode: "123",
        secondaryQCode: "1",
        type: "Number",
        questionPageId: "qp-1",
        secondaryLabel: null,
      },
      {
        title: "<p>Questions 1</p>",
        alias: undefined,
        nested: true,
        id: "ans-p1-2",
        description: "",
        guidance: "",
        label: "curr1",
        qCode: "123",
        secondaryQCode: "2",
        type: "Currency",
        questionPageId: "qp-1",
        secondaryLabel: null,
      },
      {
        title: "<p>Questions 1</p>",
        alias: undefined,
        nested: true,
        id: "ans-p1-3",
        description: "",
        guidance: "",
        label: "Un1",
        qCode: "1",
        secondaryQCode: "3",
        type: "Unit",
        questionPageId: "qp-1",
        secondaryLabel: null,
      },
      {
        title: "<p>Questions 1</p>",
        alias: undefined,
        nested: true,
        id: "ans-p1-4",
        description: "",
        guidance: "",
        label: "Per1",
        qCode: "2",
        secondaryQCode: "4",
        type: "Percentage",
        questionPageId: "qp-1",
        secondaryLabel: null,
      },
      {
        title: "<p>Questions 1</p>",
        alias: undefined,
        nested: true,
        id: "ans-p1-5",
        description: "",
        guidance: "",
        label: "Dur1",
        qCode: "3",
        secondaryQCode: "5",
        type: "Duration",
        questionPageId: "qp-1",
        secondaryLabel: null,
      },
      {
        title: "<p>Questions 1</p>",
        alias: undefined,
        nested: true,
        id: "ans-p1-6",
        description: "",
        guidance: "",
        label: "Num2",
        qCode: "4",
        secondaryQCode: "5",
        type: "Number",
        questionPageId: "qp-1",
        secondaryLabel: null,
      },
      {
        title: "<p>Questions 1</p>",
        alias: undefined,
        nested: true,
        id: "ans-p7-1",
        description: "",
        guidance: "",
        label: "",
        qCode: "5",
        type: "Checkbox",
        questionPageId: "29ceee38-5ba4-4f43-84ae-0162c5b175f8",
        options: [[Object], [Object]],
        mutuallyExclusiveOption: {
          id: "cb-3",
          label: "Embedded checkbox Or",
          mutuallyExclusive: true,
          description: null,
          additionalAnswer: null,
          qCode: "29",
        },
      },
      {
        title: "<p>Questions 1</p>",
        alias: undefined,
        nested: true,
        id: "cb-1",
        label: "Embedded checkbox Either",
        description: null,
        additionalAnswer: null,
        qCode: "27",
        type: "CheckboxOption",
        option: true,
      },
      {
        title: "<p>Questions 1</p>",
        alias: undefined,
        nested: true,
        id: "cb-2",
        label: "Either 2",
        description: null,
        additionalAnswer: null,
        qCode: "28",
        type: "CheckboxOption",
        option: true,
      },
      {
        title: "<p>Questions 1</p>",
        alias: undefined,
        nested: true,
        id: "cb-3",
        label: "Embedded checkbox Or",
        mutuallyExclusive: true,
        description: null,
        additionalAnswer: null,
        qCode: "29",
        type: "MutuallyExclusiveOption",
        option: true,
      },
      {
        title: "<p>Questions 2</p>",
        alias: undefined,
        id: "ans-p2-1",
        description: "",
        guidance: "",
        label: "Da1",
        qCode: "",
        secondaryQCode: "6",
        type: "Date",
        questionPageId: "qp-2",
        secondaryLabel: null,
      },
      {
        title: "<p>Questions 3</p>",
        alias: undefined,
        id: "ans-p3-1",
        description: "",
        guidance: "",
        label: "To",
        secondaryLabel: "From",
        qCode: "6",
        secondaryQCode: "99",
        type: "DateRange",
        questionPageId: "qp-3",
      },
      {
        title: "<p>Questions 3</p>",
        alias: undefined,
        nested: true,
        id: "ans-p3-1",
        label: "From",
        qCode: "99",
        type: "DateRange",
        validationErrorInfo: undefined,
        secondary: true,
      },
      {
        title: "<p>Questions 4</p>",
        alias: undefined,
        id: "ans-p4-1",
        description: "",
        guidance: "",
        label: "TF",
        qCode: "",
        secondaryQCode: "7",
        type: "TextField",
        questionPageId: "qp-4",
        secondaryLabel: null,
      },
      {
        title: "<p>Questions 4</p>",
        alias: undefined,
        nested: true,
        id: "ans-p4-2",
        description: "",
        guidance: "",
        label: "TA",
        qCode: "",
        secondaryQCode: "8",
        type: "TextArea",
        questionPageId: "qp-4",
        secondaryLabel: null,
      },
      {
        title: "<p>Questions 5</p>",
        alias: undefined,
        id: "conf-q-1",
        qCode: "10",
        type: "QuestionConfirmation",
        validationErrorInfo: undefined,
      },
      {
        title: "<p>Questions 7</p>",
        alias: null,
        id: "ans-p6-1",
        description: "",
        guidance: "",
        label: "",
        qCode: "",
        type: "Radio",
        questionPageId: "qp-6",
        options: [[Object], [Object]],
      },
      {
        title: "<p>Questions 8</p>",
        alias: undefined,
        id: "ans-p7-1",
        description: "",
        guidance: "",
        label: "",
        qCode: "1238",
        type: "Checkbox",
        questionPageId: "29ceee38-5ba4-4f43-84ae-0162c5b175f8",
        options: [[Object], [Object]],
        mutuallyExclusiveOption: {
          id: "option-cb-2",
          label: "Or",
          mutuallyExclusive: true,
          description: null,
          additionalAnswer: null,
          qCode: "20",
        },
      },
      {
        title: "<p>Questions 8</p>",
        alias: undefined,
        nested: true,
        id: "option-cb-1",
        label: "Either",
        description: null,
        additionalAnswer: null,
        qCode: "9",
        type: "CheckboxOption",
        option: true,
      },
      {
        title: "<p>Questions 8</p>",
        alias: undefined,
        nested: true,
        id: "option-cb-3",
        label: "Either 2",
        description: null,
        additionalAnswer: null,
        qCode: "chk",
        type: "CheckboxOption",
        option: true,
      },
      {
        title: "<p>Questions 8</p>",
        alias: undefined,
        nested: true,
        id: "option-cb-2",
        label: "Or",
        mutuallyExclusive: true,
        description: null,
        additionalAnswer: null,
        qCode: "20",
        type: "MutuallyExclusiveOption",
        option: true,
      },
    ];
```

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/qcodes/QCodesTable/index.test.js
> +  ];
The formatting is a bit weird here

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/qcodes/QCodesTable/index.test.js
> +  ];
```
     {
        title: "<p>Questions 1</p>",
        alias: undefined,
        id: "ans-p1-1",
        description: "",
        guidance: "",
        label: "num1",
        qCode: "123",
        secondaryQCode: "1",
        type: "Number",
        questionPageId: "qp-1",
        secondaryLabel: null,
      }
```

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/qcodes/QCodesTable/index.test.js
> +  duplicates = {123: 2};
```suggestion
  duplicates = { 123: 2 };
```

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/QuestionnaireDesignPage/MainNavigation/index.test.js
> +    // duplicates = {qCode3: 2};
```suggestion
```

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/QuestionnaireDesignPage/MainNavigation/index.test.js
> +    // duplicates = {qCode3: 2};
The `flattenedAnswer` format is also off here

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/QuestionnaireDesignPage/MainNavigation/index.test.js
> +         <QCodeContext.Provider value={{flattenedAnswers, duplicateQCode}}>
```suggestion
         <QCodeContext.Provider value={{ flattenedAnswers, duplicateQCode }}>
```

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/QuestionnaireDesignPage/MainNavigation/index.test.js
> +        <QCodeContext.Provider value={{flattenedAnswers, duplicateQCode}}>
```suggestion
        <QCodeContext.Provider value={{ flattenedAnswers, duplicateQCode }}>
```

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/QuestionnaireDesignPage/MainNavigation/index.test.js
> +        <QCodeContext.Provider value={{flattenedAnswers, duplicateQCode}}>
```suggestion
        <QCodeContext.Provider value={{ flattenedAnswers, duplicateQCode }}>
```

2021-02-10 08:30 UTC, tjamesmac commented on eq-author/src/App/QuestionnaireDesignPage/MainNavigation/index.test.js
> +        <QCodeContext.Provider value={{flattenedAnswers, duplicateQCode}}>
```suggestion
        <QCodeContext.Provider value={{ flattenedAnswers, duplicateQCode }}>
```

2021-02-12 11:17 UTC, farres1 approved these changes

2021-02-12 17:17 UTC, tbaggaley approved these changes

2021-02-15 09:22 UTC, merged