Ear 1007-create a question inside outside folder
ONSdigital/eq-author-app pull request #1806
Opened 2021-02-19 16:37 UTC by tjamesmac

## Additional info
Ticket
Design

### What is the context of this PR?
This is adding buttons to places
Make todo list here

### How to review
TBD

2021-03-02 10:40 UTC, MattElcock commented on eq-author/src/App/QuestionnaireDesignPage/NavigationSidebar/AddMenu/AddMenu.js
> +  let defaultButtons = [
```suggestion
  const defaultButtons = [
```

2021-03-02 10:40 UTC, MattElcock commented on eq-author/src/App/QuestionnaireDesignPage/NavigationSidebar/AddMenu/AddMenu.js
> +};
```suggestion
const FolderAddSubMenu = ({ children }) => (
    <>
      <ContentCategory>
        <div>Inside</div>
      </ContentCategory>
      {children}
      <ContentCategory>
        <div>Outside</div>
      </ContentCategory>
    </>
  );
```

2021-03-02 10:40 UTC, MattElcock commented on eq-author/src/App/QuestionnaireDesignPage/NavigationSidebar/AddMenu/AddMenuButtons.js
> +};
```suggestion
export const MenuButton = ({ handleClick, disabled, dataTest, icon, text }) => (
    <AddMenuButton
      key={dataTest}
      data-test={dataTest}
      disabled={disabled}
      onClick={handleClick}
    >
      <StyledIconText icon={icon}>{text}</StyledIconText>
    </AddMenuButton>
  );
```

2021-03-02 10:40 UTC, MattElcock commented on eq-author/src/App/QuestionnaireDesignPage/index.js
> +  // withMutations,
```suggestion
```

2021-03-12 08:26 UTC, tbaggaley approved these changes
This is all just tiny nitpicky stuff from the files I've viewed so far, all optional

Think otherwise let's just merge (once the conflicts with master are sorted)... I'm familiar with most of it and I think it's good - it's probably something that will lend itself to refinement over time if needed rather than now since it's a huge beastie

Everything seems to work okay and it's nice to see QDP having lost some weight

2021-03-12 08:26 UTC, tbaggaley commented on eq-author-api/schema/resolvers/pages/questionPage.js
> +      // why do I need folder.pages.length?
```suggestion
```

Unless this was still something to think about

2021-03-12 08:26 UTC, tbaggaley commented on eq-author-api/schema/resolvers/utils.js
> +  // TODO make this conditional?
```suggestion
```

2021-03-12 08:26 UTC, tbaggaley commented on eq-author-api/schema/typeDefs.js
> +  sectionId: ID
```suggestion
```

Don't think this is used anymore

2021-03-12 08:26 UTC, tbaggaley commented on eq-author-api/schema/typeDefs.js
> +  sectionId: ID
```suggestion
```

Ditto

2021-03-12 08:26 UTC, tbaggaley commented on eq-author/src/App/QuestionnaireDesignPage/MainNavigation/index.js
> +export default withRouter(UnwrappedMainNavigation);
Now this is a functional comp. could use `useRouter` or `useMatch` or whatever instead of using the HOC (if you want)

2021-03-12 08:26 UTC, tbaggaley commented on eq-author/src/App/QuestionnaireDesignPage/NavigationSidebar/AddMenu/AddMenu.js
> +    <>
```suggestion
```

2021-03-12 08:26 UTC, tbaggaley commented on eq-author/src/App/QuestionnaireDesignPage/NavigationSidebar/AddMenu/AddMenu.js
> +    </>
```suggestion
```

2021-03-12 08:26 UTC, tbaggaley commented on eq-author/src/App/QuestionnaireDesignPage/NavigationSidebar/NavigationHeader.js
> +export default withRouter(WrappedHeader);
Could use `useRouter`, optional obvs

2021-03-12 14:29 UTC, MattElcock requested changes

2021-03-12 14:55 UTC, tjamesmac commented on eq-author/src/App/QuestionnaireDesignPage/NavigationSidebar/AddMenu/FolderSubMenu.js
> +  </>
The fragment is needed because it is three components together

2021-03-12 15:08 UTC, MattElcock requested changes
If I am focused on a folder and the folder already has question pages in it, when I add a new question page into the folder the insert animation shows for all pages beneath the one I'm adding.

2021-03-12 15:21 UTC, MattElcock requested changes
Adding a question page goes to the top of a folder (which is right). But, adding a Calculated Summary goes to the bottom. Is that right? I can't see any AC on the ticket that defined Calc Sum behaviour.

2021-03-12 16:44 UTC, tjamesmac commented
@MattElcock in regards to the calculated summary going at the bottom. It's copying the behaviour of adding a calc sum from a section. It's a summary of the questions before it right, wouldn't make sense for it to go first. 

Also fixed the animation

2021-03-15 10:05 UTC, jasehumphr submitted a review, later dismissed
hasTick

2021-03-16 08:53 UTC, jasehumphr submitted a review, later dismissed

2021-03-16 09:45 UTC, MattElcock approved these changes
Amazeballs. Well done, mate. Looking good.

2021-03-16 09:52 UTC, tbaggaley approved these changes

2021-03-16 09:54 UTC, MattElcock approved these changes

2021-03-16 09:55 UTC, jasehumphr approved these changes
SWEET

2021-03-16 09:58 UTC, merged