EAR 1072 QCodes on/off
ONSdigital/eq-author-app pull request #1941
Opened 2021-04-07 12:37 UTC by farres1

> BEFORE MAKING YOUR PR... There must be no linting errors, all tests must pass and PR is named after JIRA ticket number e.g. EAR-###.

### What is the context of this PR?

> Describe what you have changed as part of this task and why; include a link to the Trello card/GitHub issue, related pull requests, etc as required.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2021-04-13 08:14 UTC, tjamesmac requested changes
All looks great Sam, just need a test or two to support the qCode toggling on the `GeneralSettingsPage`

2021-04-13 11:24 UTC, tbaggaley requested changes
Looking good Sam, works well.

Just one small suggestion.

Might be a good idea to add a migration so existing questionnaires have the toggle turned on - otherwise might confuse people when this goes live and they lose access to the qcodes page. I know it's not in the AC though

2021-04-13 11:24 UTC, tbaggaley commented on eq-author/src/App/QuestionnaireDesignPage/MainNavigation/index.js
> +                  (qcodesEnabled && duplicateQCode === true) ? (
Just a little one

```suggestion
                  {qcodesEnabled && (emptyQCode || duplicateQCode) ? (
```

2021-04-14 09:36 UTC, tbaggaley submitted a review, later dismissed

2021-04-15 08:22 UTC, tjamesmac requested changes
Hi Sam, sorry one more test please, could you assert that when `questionnaire.qCodes` is true or false, that the qCodes button in the main navigation is in fact disabled

2021-04-15 14:31 UTC, tjamesmac approved these changes
Nice one!

2021-04-16 07:02 UTC, jasehumphr approved these changes
Lovely Sam

2021-04-16 07:17 UTC, merged