Ear 1033 validate other label radio and checkbox
ONSdigital/eq-author-app pull request #1973
Opened 2021-04-19 08:23 UTC by zimboflyman

> BEFORE MAKING YOUR PR... There must be no linting errors, all tests must pass and PR is named after JIRA ticket number e.g. EAR-###.

### What is the context of this PR?

> Describe what you have changed as part of this task and why; include a link to the Trello card/GitHub issue, related pull requests, etc as required.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2021-04-29 09:29 UTC, MattElcock requested changes

2021-04-29 09:29 UTC, MattElcock commented on eq-author/src/App/page/Design/answers/MultipleChoiceAnswer/MultipleChoiceAnswer.test.js
> +  // });
```suggestion
```

2021-04-29 09:37 UTC, MattElcock commented
![image](https://user-images.githubusercontent.com/15129656/116531158-c8302c00-a8d6-11eb-8682-0eb3b1ce1665.png)

The distance between the error message and the bottom of the component needs to be increased a smidge, I think.

2021-04-29 09:49 UTC, zimboflyman commented on eq-author/src/App/page/Design/answers/MultipleChoiceAnswer/MultipleChoiceAnswer.test.js
> +  // });
woops - now sorted

2021-04-29 10:00 UTC, MattElcock submitted a review, later dismissed
Hi Shane, well done on this. Thanks, too, for modernising the class component. It's good to see that we're making these improvements when we come across them.

Everything looks nice, tidy, and works as expected. :)

2021-04-29 10:04 UTC, farres1 reviewed
The validation is really good!

I agree with Matt that the error message should be slightly higher. 

Also, the validation error message for unique radio/checkboxes no longer works. The error badge is still displayed, but the error message is not shown.

2021-04-29 15:41 UTC, tbaggaley requested changes

2021-04-29 15:41 UTC, tbaggaley commented on .gitignore
> +env.*local
```suggestion
```

Haven't looked properly yet but can we get rid of these from the `.gitignore`? :-)

2021-04-30 08:04 UTC, farres1 approved these changes

2021-04-30 08:35 UTC, MattElcock approved these changes

2021-04-30 08:42 UTC, merged