Ear 1348 section settings for hub
ONSdigital/eq-author-app pull request #2140
Opened 2021-07-01 15:55 UTC by zimboflyman

### What is the context of this PR?

**Acceptance criteria (user perspective)**

1. Mandatory section

GIVEN I am on the section page
WHEN the navigation is set to section navigation or none
THEN I don't see the mandatory section toggle

GIVEN I am on the section page
WHEN I have enabled hub navigation 
THEN I see the mandatory section toggle

GIVEN I have enabled hub navigation
ANDF i am on the section page
WHEN I set the mandatory section toggle
THEN that section will be set as mandatory section

GIVEN I have enabled hub navigation
AND i am on the section page
WHEN I unset the mandatory section toggle
THEN that section will not be set as mandatory section

2. Show on hub

GIVEN I have enabled hub navigation
AND i am on the section page
WHEN I set the mandatory section toggle
THEN the show on hub toggle will be visible

GIVEN I have enabled hub navigation
AND i am on the section page
WHEN I unset the mandatory section toggle
THEN the show on hub toggle will not be visible

GIVEN I have enabled hub navigation
AND i am on the section page
AND I set the mandatory section toggle
WHEN I set the show on hub toggle
THEN that section will appear on the hub

GIVEN I have enabled hub navigation
AND i am on the section page
AND I set the mandatory section toggle
WHEN I unset the show on hub toggle
THEN that section will not appear on the hub

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2021-07-06 10:09 UTC, martyncolmer submitted a review, later dismissed

2021-07-06 11:05 UTC, tbaggaley requested changes
Will we need a migration to set `showOnHub` to be `true` for existing questionnaires? They'll act as if it were `false` otherwise (so presumably both toggles will show as disabled initially on existing ones).

Haven't actually tried it out yet, just looking at code.

2021-07-06 11:17 UTC, martyncolmer commented
> Will we need a migration to set `showOnHub` to be `true` for existing questionnaires? They'll act as if it were `false` otherwise (so presumably both toggles will show as disabled initially on existing ones).
> 
> Haven't actually tried it out yet, just looking at code.

Migrated questionnaires work ok and will be edge cases, i'm happy for it not to be defaulted in that situation.

2021-07-06 11:29 UTC, martyncolmer commented
> Will we need a migration to set `showOnHub` to be `true` for existing questionnaires? They'll act as if it were `false` otherwise (so presumably both toggles will show as disabled initially on existing ones).
> 
> Haven't actually tried it out yet, just looking at code.

Yes, we will need a migration to add both requiredCompleate and showOnHub

2021-07-07 09:16 UTC, martyncolmer approved these changes

2021-07-07 09:22 UTC, tbaggaley approved these changes

2021-07-07 09:39 UTC, merged