✨ EAR 1318 - Create design for `review questions`
ONSdigital/eq-author-app pull request #2165
Opened 2021-07-08 11:40 UTC by tbaggaley

# WIP

### What is the context of this PR?

> Describe what you have changed as part of this task and why; include a link to the Trello card/GitHub issue, related pull requests, etc as required.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2021-07-12 08:50 UTC, MattElcock requested changes
Hey Tom.

Code looks great; I love the storybook file. 😂

Some tweaks for the design;

- The back button doesn't match the design quite right (colour is blue where it should be grey, text isn't bold and the chevron isn't quite the same;
- The close 'x' button is blue where it should be grey;
- The onFocus styles for the following buttons aren't consistent with the rest of the app (you can import `focusStyles` from `theme.js` and use that to ensure they're all the same);
- - 'Remove all'
- - 'x' to remove a selected question
- - 'Select questions'
- - 'Import'
- - 'Cancel'

I also noticed that some of the clickable elements change the cursor when you hover over them (great) but don't change colour like other elements, is that intentional? Not sure if they all need to change colour onHover if we have the cursor changing, as it might be enough. Thought I'd mention it just in case 'though. (The elements are the 'back' button, 'remove all' text and the 'x' on questions.)

2021-07-12 11:25 UTC, tbaggaley commented
> Hey Tom.
> 
> Code looks great; I love the storybook file. 😂
> 
> Some tweaks for the design;
> 
> * The back button doesn't match the design quite right (colour is blue where it should be grey, text isn't bold and the chevron isn't quite the same; ✅
> * The close 'x' button is blue where it should be grey; ✅
> * The onFocus styles for the following buttons aren't consistent with the rest of the app (you can import `focusStyles` from `theme.js` and use that to ensure they're all the same); 
> * * 'Remove all' ✅
> * * 'x' to remove a selected question ✅
> * * 'Select questions' ✅
> * * 'Import' ✅
> * * 'Cancel' ✅
> 
> I also noticed that some of the clickable elements change the cursor when you hover over them (great) but don't change colour like other elements, is that intentional? Not sure if they all need to change colour onHover if we have the cursor changing, as it might be enough. Thought I'd mention it just in case 'though. (The elements are the 'back' button, 'remove all' text and the 'x' on questions.) ✅

Cheers Matt!

Styling changes implemented. Let me know if you still think anything needs tweaking.

I've added the `focusStyle` to `components/Button` so that buttons have that styling by default. Also changed `border-color: none` to `border-color: transparent` while I was in there because Chrome was complaining that `none` wasn't a valid property value - hence all the snapshot updates.

2021-07-12 12:47 UTC, MattElcock approved these changes

2021-07-14 08:35 UTC, ashtuck approved these changes
Followed the steps check. Matches the expected behaviour.

2021-07-14 08:35 UTC, merged