Ear 1319 construct importing process
ONSdigital/eq-author-app pull request #2191
Opened 2021-07-26 07:59 UTC by MattElcock

> ### BEFORE MAKING YOUR PR
>
> Please ensure:
>
> - There are no linting errors, all tests must pass
> - PR is named after JIRA ticket number e.g. EAR-###
> - **Accesibility** checks are completed:
>   - Elements have discernible and consistent focus states
>   - Elements can be navigated to and used by just a keyboard
>   - Elements and text can be read out by a screen reader, and the descriptions are understandable
> - Your feature / bug fix works across **GCP** and **AWS** (where appropriate)
>   - Are modifications to eq-publisher-v3 required?
>   - Are modifications to the Firestore data source required?

---

### What is the context of this PR?

> Describe what you have changed as part of this task and why; include a link to the Trello card/GitHub issue, related pull requests, etc as required.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2021-08-03 09:58 UTC, ashtuck submitted a review, later dismissed

2021-08-05 08:16 UTC, MattElcock commented
After speaking with Sam:

- [ ] Modified date shows 'invalid date'
- [ ] Importing a source questionnaire from 'Editor' pane doesn't work
- [ ] Cannot scroll with lots of questionnaires on 'All' page,
- [ ] 'Showing x of y' not indented
- [ ] Owner on source questionnaire isn't populated
- [ ] When page 1 of 1 the right arrow is clickable when it shouldn't be

2021-08-05 08:23 UTC, farres1 requested changes
Requesting changes as I've discussed some bugs with Matt to fix before this ticket is merged.

Matt has a list of these bugs in the above comment.

2021-08-05 08:50 UTC, farres1 commented on eq-author/src/App/importingContent/index.js
> +            console.log(data.questionnaires);
console log

2021-08-05 08:57 UTC, farres1 reviewed
Deleting a questionnaire from the home page requires a refresh before it's removed from the table of questionnaires.

2021-08-05 10:32 UTC, farres1 commented on eq-author/src/components/QuestionnaireTable/index.js
> +    variant == "selectModal" &&
```suggestion
    variant === "selectModal" &&
```

2021-08-05 10:36 UTC, farres1 commented on eq-author/src/components/QuestionnairesView/PaginationNav/index.js
> +    padding == "small" &&
```suggestion
    padding === "small" &&
```

2021-08-05 10:45 UTC, farres1 requested changes

2021-08-05 10:45 UTC, farres1 commented on eq-author/src/components/QuestionnairesView/PaginationNav/index.js
> +  padding,
`padding` missing from props validation

2021-08-05 10:45 UTC, farres1 commented on eq-author/src/components/QuestionnaireTable/index.js
> +  variant,
`variant` missing from props validation

2021-08-06 09:35 UTC, farres1 approved these changes

2021-08-09 14:13 UTC, zimboflyman approved these changes
Monster PR - nice job Matt! 😊

2021-08-09 14:13 UTC, merged