EAR-1469  disabled toggle if no summary
ONSdigital/eq-author-app pull request #2306
Opened 2021-09-23 08:09 UTC by jasehumphr

> ### BEFORE MAKING YOUR PR
>
> Please ensure:
>
> - There are no linting errors, all tests must pass
> - PR is named after JIRA ticket number e.g. EAR-###
> - **Accesibility** checks are completed:
>   - Elements have discernible and consistent focus states
>   - Elements can be navigated to and used by just a keyboard
>   - Elements and text can be read out by a screen reader, and the descriptions are understandable
> - Your feature / bug fix works across **GCP** and **AWS** (where appropriate)
>   - Are modifications to eq-publisher-v3 required?
>   - Are modifications to the Firestore data source required?

---

### What is the context of this PR?

> Describe what you have changed as part of this task and why; include a link to the Trello card/GitHub issue, related pull requests, etc as required.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2021-09-23 08:45 UTC, MattElcock approved these changes

2021-09-23 08:45 UTC, MattElcock commented on eq-author/src/App/section/Design/SectionEditor/SectionSummary/index.js
> +              disabled="true"
Should this always be set to disabled?

2021-09-23 08:46 UTC, MattElcock requested changes
You haven't written any tests.

2021-09-23 08:47 UTC, MattElcock requested changes

2021-09-23 08:47 UTC, MattElcock commented on eq-author/src/App/section/Design/SectionEditor/SectionSummary/index.js
> +              disabled="true"
Should this always be disabled?

2021-09-23 08:58 UTC, ashtuck approved these changes

2021-10-05 12:26 UTC, martyncolmer requested changes

2021-10-05 12:26 UTC, martyncolmer commented on eq-author/src/App/section/Design/SectionEditor/HubSettings/index.test.js
> +      sectionSummary: false,
Didn't need to add this and collapsible summery here.

2021-10-05 12:27 UTC, martyncolmer commented on eq-author/src/App/section/Design/SectionEditor/HubSettings/index.test.js
> +      sectionSummary: false,
You can remove sectionSummary and collapsible summary, their redundant,

2021-10-05 12:30 UTC, farres1 reviewed
The feature looks really good! There was one bug I noticed.

1 - Enable section summary
2 - Enable collapsible summary
3 - Disable section summary

The collapsible summary toggle cannot be clicked, but the collapsible summary toggle remains enabled (its value is `true` in the JSON data)

2021-10-06 08:56 UTC, farres1 approved these changes

2021-10-06 08:58 UTC, ashtuck approved these changes

2021-10-06 09:18 UTC, merged