Update to pass an error if meta data has been deleted in `Additional …
ONSdigital/eq-author-app pull request #2315
Opened 2021-09-28 15:03 UTC by ashtuck

### Context of PR ###

When piping in MetaData into the `Additional Contents` `Question Description`, if that MetaData was then deleted, the errors don't pass down meaning it isn't obvious to the user that there's an error.

### How to review ###

- Create a question and answer.
- Add a `Question Description` text.
- Create a custom MetaData.
- Pipe that MetaData into the  `Question Description`.
-  Then delete that MetaData tag and you should see the errors appear in the Design Page.

What to do after everything is green
    *   Bring this branch up-to-date with Origin/Master
    *   If there are a lot of commits or some are not helpful to read, squash them down
    *   Click the Merge button on this pull request
    *   Does this change mean the Capability examples questionnaire should be updated?
    *   Move the Jira ticket for this task into the next stage of the process

2021-09-28 15:34 UTC, farres1 requested changes
The error badge is being displayed correctly in the navigation bar, however the error message is not displayed on the design page. I think the question description text editor's border will also need to be changed to the error primary colour when there is an error

2021-09-29 10:07 UTC, ashtuck commented
Error message issue is now fixed.

2021-09-29 14:15 UTC, farres1 approved these changes

2021-10-04 10:08 UTC, MattElcock approved these changes

2021-10-04 10:28 UTC, merged