Ear 404 new feature route skip on num 0f chkbxs selected
ONSdigital/eq-author-app pull request #2417
Opened 2021-11-23 18:00 UTC by zimboflyman

https://collaborate2.ons.gov.uk/jira/browse/EAR-404

### What is the context of this PR?

To Be able to route out based on the number of checkbox options selected.

Q: Which of the following pets do you have:

Rabbits, dogs, cats, hamsters, fish

Routing: If someone selects 2 or more checkboxes, go here, else go there.

### How to review

2021-12-09 15:08 UTC, jasehumphr approved these changes

2021-12-14 12:40 UTC, farres1 requested changes

2021-12-14 12:40 UTC, farres1 commented on eq-author/src/App/page/Logic/BinaryExpressionEditor/SecondaryConditionSelector.js
> +          >
Would also require import to be removed from the other review suggestion

2021-12-14 12:40 UTC, farres1 commented on eq-author/src/App/page/Logic/BinaryExpressionEditor/SecondaryConditionSelector.js
> +import VisuallyHidden from "components/VisuallyHidden";
```suggestion

```

Would also require the other suggestion to be implemented

2021-12-14 13:09 UTC, farres1 submitted a review, later dismissed

2021-12-14 15:29 UTC, farres1 approved these changes

2021-12-15 08:29 UTC, farres1 approved these changes

2021-12-15 09:34 UTC, ashtuck approved these changes

2021-12-15 09:52 UTC, merged