Ear 1564 themed panel component
ONSdigital/eq-author-app pull request #2419
Opened 2021-11-24 11:16 UTC by oms09

> ### BEFORE MAKING YOUR PR
>
> Please ensure:
>
> - There are no linting errors, all tests must pass
> - PR is named after JIRA ticket number e.g. EAR-###
> - **Accesibility** checks are completed:
>   - Elements have discernible and consistent focus states
>   - Elements can be navigated to and used by just a keyboard
>   - Elements and text can be read out by a screen reader, and the descriptions are understandable
> - Your feature / bug fix works across **GCP** and **AWS** (where appropriate)
>   - Are modifications to eq-publisher-v3 required?
>   - Are modifications to the Firestore data source required?

---

### What is the context of this PR?

> Describe what you have changed as part of this task and why; include a link to the Trello card/GitHub issue, related pull requests, etc as required.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2021-12-06 09:49 UTC, zimboflyman reviewed
All looks good except one small thing.
According to the design system - the error with header panel should have each error as a lin
![Err panel Example](https://user-images.githubusercontent.com/6759437/144824699-8e5acd31-fb38-4914-946d-a29fd738d9df.png)
k?

2021-12-06 12:23 UTC, oms09 commented
> All looks good except one small thing. According to the design system - the error with header panel should have each error as a lin ![Err panel Example](https://user-images.githubusercontent.com/6759437/144824699-8e5acd31-fb38-4914-946d-a29fd738d9df.png) k?

2021-12-06 12:51 UTC, martyncolmer requested changes

2021-12-06 12:51 UTC, martyncolmer commented on eq-author/src/components-themed/panels/panel.js
> +            <StyledImage src={icon} />
As the success icon doesn't change, we should hard code it rather than pass it as a prop.

2021-12-06 14:59 UTC, martyncolmer commented on eq-author/src/components-themed/panels/panel.js
> +            <StyledImage src={icon} />
Also don't need the img tag if we are just importing the svg

2021-12-06 15:22 UTC, zimboflyman submitted a review, later dismissed
Nice!

2021-12-06 16:25 UTC, martyncolmer requested changes

2021-12-06 16:25 UTC, martyncolmer commented on eq-author/src/components-themed/panels/panel.js
> +  type: "panel",
Don't need to set the type

2021-12-09 10:07 UTC, zimboflyman approved these changes

2021-12-13 11:23 UTC, martyncolmer approved these changes

2021-12-13 11:23 UTC, merged