EAR-1559-header component
ONSdigital/eq-author-app pull request #2420
Opened 2021-11-25 14:03 UTC by shelleytruong

> ### BEFORE MAKING YOUR PR
>
> Please ensure:
>
> - There are no linting errors, all tests must pass
> - PR is named after JIRA ticket number e.g. EAR-###
> - **Accesibility** checks are completed:
>   - Elements have discernible and consistent focus states
>   - Elements can be navigated to and used by just a keyboard
>   - Elements and text can be read out by a screen reader, and the descriptions are understandable
> - Your feature / bug fix works across **GCP** and **AWS** (where appropriate)
>   - Are modifications to eq-publisher-v3 required?
>   - Are modifications to the Firestore data source required?

---

### What is the context of this PR?

> Describe what you have changed as part of this task and why; include a link to the Trello card/GitHub issue, related pull requests, etc as required.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2021-11-30 14:37 UTC, ashtuck submitted a review, later dismissed

2021-11-30 17:43 UTC, martyncolmer requested changes
Noted a few things. 
Some additional things we will want to discuss. 
Theres no option to have side content such as a button.
Theres no option to have list options on the bottom of the header.

2021-11-30 17:43 UTC, martyncolmer commented on eq-author/src/components-themed/Header/index.js
> +  padding-left: 18px;
Can we make this 1 rem and have the padding on the right as well.

2021-12-01 18:22 UTC, martyncolmer commented on eq-author/src/components-themed/Header/index.js
> +      <HeaderTop variant={variant} exampleList={exampleList}>
Don't think you need to pass in example list here as not used by css

2021-12-01 18:22 UTC, martyncolmer commented on eq-author/src/components-themed/Header/index.js
> +  exampleList,
need a better name like headerTopContent

2021-12-01 20:35 UTC, martyncolmer requested changes

2021-12-01 20:35 UTC, martyncolmer commented on eq-author/src/components-themed/Header/index.js
> +      font-size: 1rem;
add this to move the underline lower
text-underline-position: under;

2021-12-13 11:20 UTC, ashtuck approved these changes

2021-12-13 11:26 UTC, martyncolmer approved these changes

2021-12-13 11:27 UTC, ashtuck approved these changes

2021-12-13 11:32 UTC, merged