Ear 636 bypass blocks of content
ONSdigital/eq-author-app pull request #2422
Opened 2021-11-29 10:13 UTC by jasehumphr

> ### BEFORE MAKING YOUR PR
>
> Please ensure:
>
> - There are no linting errors, all tests must pass
> - PR is named after JIRA ticket number e.g. EAR-###
> - **Accesibility** checks are completed:
>   - Elements have discernible and consistent focus states
>   - Elements can be navigated to and used by just a keyboard
>   - Elements and text can be read out by a screen reader, and the descriptions are understandable
> - Your feature / bug fix works across **GCP** and **AWS** (where appropriate)
>   - Are modifications to eq-publisher-v3 required?
>   - Are modifications to the Firestore data source required?

---

### What is the context of this PR?

> Describe what you have changed as part of this task and why; include a link to the Trello card/GitHub issue, related pull requests, etc as required.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2021-12-07 17:00 UTC, martyncolmer commented on eq-author/src/components/EditorLayout/Header/index.js
> +      <StyledHeader id="SuperNav-4" tabIndex="-1" className="keyNav">
id not needed

2021-12-07 17:00 UTC, martyncolmer commented on eq-author/src/components/EditorLayout/Tabs/index.js
> +    id: "SuperNav-3",
not needed

2021-12-07 18:57 UTC, martyncolmer commented on eq-author/src/App/pageskip/PageSkipPage.js
> +import React from "react";
needs a better name link KeyboardShortcutsPage

2021-12-08 00:37 UTC, martyncolmer commented on eq-author/src/App/sharing/SharePage.js
> +import styled from "styled-components";
This import is not used

2021-12-08 00:38 UTC, martyncolmer requested changes
On the design page, the tab goes to the comments pane, but there is nothing there.

2021-12-08 09:28 UTC, farres1 requested changes
It looks really good! I've added some comments in the review

2021-12-08 09:28 UTC, farres1 commented on eq-author/src/App/keyboardShortcuts/KeyboardShortcutsPage.js
> +  border-bottom: 1px ${colors.grey35};
These lines aren't visible as they aren't `solid`. Changing them to use `solid` displays them differently to the prototype as they don't touch the edges of the table.

2021-12-08 09:28 UTC, farres1 commented on eq-author/src/App/keyboardShortcuts/KeyboardShortcutsPage.js
> +const TableDataB = styled.td`
```suggestion
const TableDataDarkGrey = styled.td`
```
Suggested name change

2021-12-08 09:28 UTC, farres1 commented on eq-author/src/App/keyboardShortcuts/KeyboardShortcutsPage.js
> +const TableData = styled.td`
```suggestion
const TableDataLightGrey = styled.td`
```
Suggested name change

2021-12-09 11:41 UTC, martyncolmer approved these changes

2021-12-09 11:43 UTC, merged