Homepage Redesign
ONSdigital/eq-author-app pull request #2562
Opened 2022-02-24 17:03 UTC by shelleytruong

> ### BEFORE MAKING YOUR PR
>
> Please ensure:
>
> - There are no linting errors, all tests must pass
> - PR is named after JIRA ticket number e.g. EAR-###
> - **Accesibility** checks are completed:
>   - Elements have discernible and consistent focus states
>   - Elements can be navigated to and used by just a keyboard
>   - Elements and text can be read out by a screen reader, and the descriptions are understandable
> - Your feature / bug fix works across **GCP** and **AWS** (where appropriate)
>   - Are modifications to eq-publisher-v3 required?
>   - Are modifications to the Firestore data source required?

---

### What is the context of this PR?

> Describe what you have changed as part of this task and why; include a link to the Trello card/GitHub issue, related pull requests, etc as required.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2022-03-15 13:17 UTC, jasehumphr approved these changes

2022-03-21 11:21 UTC, jasehumphr submitted a review, later dismissed

2022-03-21 13:31 UTC, zimboflyman requested changes
Looks great/1. just an unsed bit of css to remove and a random comment thats not needed

2022-03-21 13:31 UTC, zimboflyman commented on eq-author/src/components-themed/QuestionnaireTable/index.js
> +  variant, //what is variant is it needed
can we lose this comment?  doesn't appear helpfull

2022-03-21 13:31 UTC, zimboflyman commented on eq-author/src/components/UserProfile/index.js
> +    /* color: ${colors.text}; */
can we remove this unused code?

2022-03-24 12:29 UTC, zimboflyman approved these changes

2022-03-28 08:22 UTC, jasehumphr approved these changes

2022-03-28 08:24 UTC, merged