dynamicAnswer typedefs
ONSdigital/eq-author-app pull request #2709
Opened 2022-07-14 10:12 UTC by oms09

> ### BEFORE MAKING YOUR PR
>
> Please ensure:
>
> - There are no linting errors, all tests must pass
> - PR is named after JIRA ticket number e.g. EAR-###
> - **Accesibility** checks are completed:
>   - Elements have discernible and consistent focus states
>   - Elements can be navigated to and used by just a keyboard
>   - Elements and text can be read out by a screen reader, and the descriptions are understandable
> - Your feature / bug fix works across **GCP** and **AWS** (where appropriate)
>   - Are modifications to eq-publisher-v3 required?
>   - Are modifications to the Firestore data source required?

---

### What is the context of this PR?

> Describe what you have changed as part of this task and why; include a link to the Trello card/GitHub issue, related pull requests, etc as required.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2022-08-01 09:37 UTC, farres1 requested changes
These changes are looking really good!

A change I've noticed, currently the "What is a dynamic option" collapsible is not displayed when the dynamic option is toggle switch is off. On the prototype, when the dynamic option toggle switch is off, the collapsible is displayed.

2022-08-01 12:58 UTC, farres1 requested changes
Adding a list of changes discussed during a call:

- Add the collapsible when the toggle switch is off (from the prototype)
- Add the word “question” in the collapsible sentence “Note, if only one checkbox answer exists then the radio answer question is skipped.” (from  the prototype)
- Show the “Off On” labels on the toggle switch (from the prototype)
- Replace the `<p>` tags with styled components to improve consistency with other components
- Remove the `useCurrentPageId.mockImplementation(() => "1.1.2")` line in files edited where it doesn’t cause tests to break
- Add an underscore `_` in the variable `DYNAMICANSWER` to make it `DYNAMIC_ANSWER`, to follow the codebase's UPPER_CASE format and improve readability

2022-08-01 14:10 UTC, farres1 approved these changes

2022-08-01 16:03 UTC, farres1 approved these changes

2022-08-01 16:09 UTC, farres1 requested changes

2022-08-01 16:09 UTC, farres1 commented on eq-author/src/App/page/Design/answers/MultipleChoiceAnswer/Option.test.js
> +import { useCurrentPageId } from "components/RouterContext";
```suggestion

```
This line can now be removed as useCurrentPageId is no longer user

2022-08-01 16:09 UTC, farres1 commented on eq-author/src/App/page/Design/answers/MultipleChoiceAnswer/index.test.js
> +import { useCurrentPageId } from "components/RouterContext";
```suggestion

```
This line can now be removed as useCurrentPageId is no longer user

2022-08-02 09:58 UTC, farres1 approved these changes

2022-08-02 10:05 UTC, ashtuck approved these changes

2022-08-03 10:50 UTC, ashtuck approved these changes

2022-08-08 07:57 UTC, farres1 approved these changes

2022-08-08 09:07 UTC, ashtuck approved these changes

2022-08-08 10:11 UTC, merged