EAR 1751 Preview questions on introduction page
ONSdigital/eq-author-app pull request #2768
Opened 2022-09-22 09:28 UTC by farres1

…iew page

> ### BEFORE MAKING YOUR PR
>
> Please ensure:
>
> - There are no linting errors, all tests must pass
> - PR is named after JIRA ticket number e.g. EAR-###
> - **Accesibility** checks are completed:
>   - Elements have discernible and consistent focus states
>   - Elements can be navigated to and used by just a keyboard
>   - Elements and text can be read out by a screen reader, and the descriptions are understandable
> - Your feature / bug fix works across **GCP** and **AWS** (where appropriate)
>   - Are modifications to eq-publisher-v3 required?
>   - Are modifications to the Firestore data source required?

---

### What is the context of this PR?

> Describe what you have changed as part of this task and why; include a link to the Trello card/GitHub issue, related pull requests, etc as required.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Import the **Capability examples** questionnaire from pre-prod Author into your local environment and:
  - ensure it can be opened in Author;
  - then, ensure it can be viewed in Runner by pressing the **view survey** button
- Does this require a migration? We need one if existing JSON schema properties change

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2022-09-23 13:23 UTC, martyncolmer submitted a review, later dismissed

2022-09-23 15:16 UTC, Paul-Joel requested changes
All works as expected, but the text description under the buttons looks like the wrong colour - it's light grey and I think it should be black

<img width="914" alt="image" src="https://user-images.githubusercontent.com/19411155/191994800-97bc7046-d958-4ee3-a9ea-a34064c4f7a2.png">

2022-09-26 08:58 UTC, farres1 commented
> All works as expected, but the text description under the buttons looks like the wrong colour - it's light grey and I think it should be black
> 
> <img alt="image" width="914" src="https://user-images.githubusercontent.com/19411155/191994800-97bc7046-d958-4ee3-a9ea-a34064c4f7a2.png">

I held a call with the interaction designer, he has said that all of the descriptions in the introduction page should be converted from grey to black, including pre-existing ones. I have added the code to convert all of the grey descriptions into black.

2022-09-26 09:09 UTC, martyncolmer approved these changes

2022-09-26 10:13 UTC, merged