EAR-1965 - Update Content Picker v3
ONSdigital/eq-author-app pull request #2882
Opened 2023-01-17 11:34 UTC by sudeepkunhis

Signed-off-by: sudeep <sudeep.kunhikannan@ons.gov.uk>

### What is the context of this PR?

https://jira.ons.gov.uk/browse/EAR-1965

### How to review

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2023-01-23 14:43 UTC, Paul-Joel submitted a review, later dismissed

2023-01-25 09:50 UTC, farres1 requested changes

2023-01-25 09:50 UTC, farres1 commented on eq-author/src/components/ContentPickerv3/MetadataPicker.test.js
> +    );
```suggestion
  beforeEach(() => {
    props = {
      data: [
        {
          id: "91d8a289-e625-4b94-869b-a7d698be2294",
          key: "ru_name",
          alias: "Ru Name",
          type: "Text",
          textValue: "ESSENTIAL ENTERPRISE LTD.",
        },
        {
          id: "74c9ca55-dc3b-46da-b5eb-5eca48c4f443",
          key: "ref_p_start_date",
          alias: "Start Date",
          type: "Date",
          dateValue: "2016-05-01",
        },
      ],
      contentType: ANSWER,
      contentTypes: [ANSWER, METADATA],
      setContentType,
      isSelected: jest.fn(),
      onSelected: jest.fn(),
      isSectionSelected: jest.fn(),
    };
  });
  
  
  afterEach(() => {
    jest.clearAllMocks();
  });
  
  const renderMetadataPicker = () =>
    render(
      <Theme>
        <MetadataPicker {...props} />
      </Theme>
    );
```

The mock function `setContentType` is not currently being cleared after each of the tests. This means in the last test (should display metadata list), the function call test is passing as the test run before it also called the `setContentType` function with `METADATA` - moving the expect statement on line 61 to line 58 would still pass from the previous test.

Adding the suggested code will clear out the mock functions after each test is run, meaning the mock function will have to be called within each test for the test to pass.

2023-01-25 10:48 UTC, farres1 approved these changes

2023-01-25 13:27 UTC, jchapman68 approved these changes

2023-01-25 13:32 UTC, merged