EAR 1815 Answer required and mutually exclusive
ONSdigital/eq-author-app pull request #2885
Opened 2023-01-23 11:39 UTC by jchapman68

### What is the context of this PR?

> When a mutually exclusive answer is added then a banner is placed below the answer required toggle switch of the main answer to indicate that the answer required will also apply to the mutually exclusive answer.
>
> E.g. _"Currently, if you add a new question to Author the entire app crashed. This is because..."_

### How to review

> Add to the list below as appropriate, including screenshots when necessary

- Create a questions with answers of type Number, Unit, Duration, TextField, TextArea, Date, Checkbox and Select.
- For each of the above check that Answer Required has a banner below it when a Mutually Exclusive answer is added and not shown before and after the Mutually Exlusive answer is removed.
- Check that DateRange and Radio cannot have mutually exclusive answer added and that the banner is not shown below the Answer Required toggle switch.

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2023-01-23 16:33 UTC, Paul-Joel submitted a review, later dismissed

2023-01-24 14:49 UTC, masiketlamelo approved these changes

2023-01-24 14:56 UTC, sudeepkunhis requested changes
@jchapman68 
Just spotted something - in custom-prop-types/index.js and AnswerProperties/index.js - we don’t need the line for hasMutuallyExclusiveAnswer because it is not directly passed as a prop to ‘AnswerProperties’. It is present in Required/index.js. I have commented the two lines as shown below and the feature still works alright. All else looks good, okay to approve once you have a look, thanks.

2023-01-24 16:08 UTC, Paul-Joel approved these changes

2023-01-24 16:09 UTC, masiketlamelo approved these changes

2023-01-24 16:26 UTC, merged