Update Collection Lists page for EAR-2107
ONSdigital/eq-author-app pull request #3060
Opened 2023-08-30 14:04 UTC by Paul-Joel

### What is the context of this PR?
Updates to the Collection Lists page required for the List Collector work.
The changes update the usage instructions for the changes in the List Collector work

Minor tweak to Settings page to remove double left border

### How to review
Ensure the Collection Lists page, accessed via the main navigation option, matches the updated Figma for the Collection Lists page. Note that any other changes for the List Collector work are out of scope of this PR

### Links
https://www.figma.com/file/0Wre9IV3VESO2eRruHyPaU/EAR---2041-Repeating-individual-(looping)-questions-iteration-2.5?type=design&node-id=29-642&mode=design&t=J0aFK8MdeKtdubp2-0
https://jira.ons.gov.uk/browse/EAR-2246

2023-08-31 10:25 UTC, kayloshai submitted a review, later dismissed

2023-09-04 10:50 UTC, farres1 requested changes
This looks really good!

Some small differences, the text size of the headings is larger than the headings in the prototype (e.g. "List collectors and collection lists").

The margins between text blocks is larger than the margins in the prototype (between headings and text blocks, e.g. Under "What is a collection list?" heading and from "Multiple list collector questions can be linked to the same collection list." to "Each collection list requires a name and an answer template"

2023-09-05 11:21 UTC, kayloshai submitted a review, later dismissed

2023-09-07 06:42 UTC, farres1 approved these changes

2023-09-07 09:12 UTC, kayloshai approved these changes

2023-09-07 09:13 UTC, merged