EAR-2467-Supplementary-data-text-changes
ONSdigital/eq-author-app pull request #3126
Opened 2024-08-29 11:11 UTC by Farhanam76

### What is the context of this PR?

To change the text 'dataset' to 'schema'
Ticket: https://jira.ons.gov.uk/browse/EAR-2467

### How to review
 1. - [ ] Check the texts ' dataset' found in the Supplementary data are replaced with 'schema'

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2024-08-29 16:02 UTC, Paul-Joel requested changes
Changes do not match the ticket's acceptance criteria

2024-08-30 14:31 UTC, Paul-Joel submitted a review, later dismissed

2024-09-10 08:26 UTC, farres1 commented on eq-author/src/App/dataSettings/SupplementaryDataPage/schemaVersionsTable.js
> +      <Title>Datasets schema for survey ID {surveyId}</Title>
```suggestion
      <Title>Dataset schemas for survey ID {surveyId}</Title>
```
Updates the text based on the ticket. The test file will also require changes to reflect this.

2024-09-10 08:29 UTC, farres1 requested changes
The content updates look good.

I've added a small update to the text content, based on the ticket.

2024-09-10 13:34 UTC, farres1 approved these changes

2024-09-11 09:07 UTC, Paul-Joel approved these changes

2024-09-11 09:10 UTC, merged