EAR 2482 supplementary data text change
ONSdigital/eq-author-app pull request #3129
Opened 2024-10-14 08:15 UTC by Farhanam76

### What is the context of this PR?
The term "dataset" on the supplementary page needs to be updated to "dataset schema."
ticket: https://jira.ons.gov.uk/browse/EAR-2482

### How to review
On the supplementary data page, when linking to a dataset schema, ensure the following:
1) The unlink button is labeled as "unlink dataset schema."
2) After clicking the unlink button, verify that the modal refers to "dataset schema" instead of "dataset."

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2024-10-14 14:08 UTC, Paul-Joel approved these changes

2024-10-15 08:05 UTC, farres1 requested changes
The code changes look good.

I have added a text change. Also, the supplementary data page's heading currently reads as "Dataset for [SURVEY_ID]" - this can now also be updated to "Dataset schema for [SURVEY_ID]".

2024-10-15 12:11 UTC, sudeepkunhis approved these changes

2024-10-15 12:12 UTC, farres1 approved these changes

2024-10-15 12:20 UTC, merged