EAR 2529 remove leading and trailing spaces in Qcodes and value
ONSdigital/eq-author-app pull request #3133
Opened 2024-11-11 16:13 UTC by Farhanam76

### What is the context of this PR?

In the q-codes/option value page, there’s a bug where the validation error message doesn’t appear if the same qcode or value is entered with leading or trailing spaces.

ticket:  https://jira.ons.gov.uk/browse/EAR-2529

### How to review

1) In the q-Codes/Values page in Author, add an option value for answer value of a question
2) Then, add the same value with a trailing/leading space to another answer 
3) Verify that a validation error message appears to inform users that qcodes and value entries must be unique.
4) Repeat steps 1 to 3 for qCodes.
5) Verify that validation error messages are displayed in both data version 1 and data version 3.

### What to do after everything is green

1. - [ ] Bring this branch up-to-date with Origin/Master
2. - [ ] If there are a lot of commits or some are not helpful to read, squash them down
3. - [ ] Click the **Merge** button on this pull request
4. - [ ] Does this change mean the **Capability examples** questionnaire should be updated?
5. - [ ] Move the Jira ticket for this task into the next stage of the process

2024-11-21 07:44 UTC, farres1 submitted a review, later dismissed

2024-11-28 09:46 UTC, sudeepkunhis requested changes

2024-11-28 09:46 UTC, sudeepkunhis commented on eq-author/src/App/qcodes/QCodesTable/index.js
> +      const trimmedValue = value.trim().replace(/\s+/g, " ");
Please change this to `const trimmedValue = value?.trim().replace(/\s+/g, " ");`

2024-11-28 13:11 UTC, sudeepkunhis approved these changes

2024-11-29 14:43 UTC, Paul-Joel approved these changes

2024-11-29 14:45 UTC, merged